apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  namespace: weatherapp-ns
  spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-api
      role: express-api
  template:
    metadata:
      labels:
        app: express-api
        role: express-api
    spec:
      containers:
      - name: express-api
        image: davideden/weatherapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
