---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-weatherapp-traffic
  namespace: weatherapp-ns
spec:
  podSelector:
    matchLabels:
      role: weatherapp-api
  ingress:
  -  from:
     -  namespaceSelector:
          matchLabels:
            tier: expressBackend
        podSelector:
          matchLabels:
            role: weatherapp-api
